### ISSUE TITLE
Revisión arquitectura

### ISSUE THREAD

**Issue by cidinene** [Arquisoft/viade_es3c#17]
**1.Introduction   and Goal** |
1.1   Requirements Overview | realizado |  
1.2 Quality   Goals | realizado |  
1.3   Stakeholders | realizado |  
**2.Architecture   Constraints** |
**3.System Scope   and Context** | 
3.1 Business   Context | realizado |  
3.2 Technical   Context | realizado |  
**4.Solution   Strategy** | realizado con   comentarios | 

- _In this section   some decision about Map service to show routes , routes format, development   repositories should be included_

**5.Building   Block View** | 
5.1 WhiteBox   Overall System | realizado |  
5.2 Level 2 | realizado |  
5.3 Level 3. | no realizado |  
**6.RuntimeViewer** |
6.1 Runtime   Scenario 1 | realizado |  
6.2 Runtime   Scenario 2 | realizado |  
**7.Deployment   View** | 
7.1   Infraestructura Level 1 | realizado con   comentarios | 

- _I only miss   something about communication with Map Service_

7.2   Infraestructura Level 2 | realizado |  
**8.Cross-cutting   Concepts** | 
8.1   Conceptos | realizado |  
**9.Design   Decisions** | no realizado |  
**10. Quality   Requirements** | 
10.1 Quality   Tree | no realizado |  
10.2 Quality   Scenarios | realizado |  
**11. Risk and   Technical Debts** | realizado |  
**12. Glossary** | realizado |

**Comment by uo246355** [comment]
Docummentation has been reviewed in its entirety
