### ISSUE TITLE
Revisión prototipo 2

### ISSUE THREAD

**Issue by cidinene** [Arquisoft/viade_es3c#23]
Como comentado en la videoconferencia mantenida con vosotros, he tenido problemas  al visualizar rutas sin haber creado previamente ninguna. Lo demás funciona bien, permite crear rutas a través del mapa, guardar imágenes, ver las rutas. Funciona muy bien lo de compartir, con el envío de notificación del usuario. Del mismo modo que habéis añadido la posibilidad de crear amigos desde el interfaz, lo cual es muy útil :-). 
 A continuación os presento un listado de cosas que debéis mejorar:
 - Resolver el problema de que si no se ha creado ninguna ruta o haya una errónea no se quede colgado, que muestre un mensaje. 
Cosas que podéis mejorar cara a la presentación:
 - Cuando se sube una imagen se debería mostrar un mensaje o un indicador de que ya está guardado en el pod.
- Modificar una ruta ya creada.
 - Poder subir /descargar en fichero

Felicitaros por haber conseguido trabajar en equipo, aunque el trabajo ha sido muy desigualdad entre vosotros. La documentación ha sido actualizada y rectificado lo indicado en la primera revisión . Me faltaría ver el detalle técnico de uno de los puntos fuertes de vuestra aplicación :   compartir rutas (como se guardan y otorgan los accesos, las notificaciones..) hay pruebas unitarias. Faltan pruebas de aceptación. Felicidades por el trabajo conseguido.

Un saludo

**Comment by uo246355** [comment]
El prototipo ha sido revisado y se han solucionado los problemas mencionados
