### ISSUE TITLE
Create a route with a file

### ISSUE THREAD

**Issue by saragarciarg** [Arquisoft/viade_es3c#40]
The users can create a route using a geojson file and can upload multimedia too

**Comment by saragarciarg** [comment]
When press upload photo or video, url is modified to 
http://localhost:3000/?description=#/uploadRoute
The same component is been used by NewRoute and that is not happening.

**Comment by saragarciarg** [comment]
Now i'm trying to create a route with a gpx file

**Comment by saragarciarg** [comment]
To upload the files I tried to use a drag and drop but the way to treat the files was not functional, so I returned to the classic way of uploading a file

**Comment by saragarciarg** [comment]
When testing, I can't find a way to pass the file correctly. I investigated how to change the state of an object from the test but I can't get it to work.
I was looking in:
https://medium.com/@yevgen4/way-to-test-react-usestate-hook-with-jest-and-enzyme-acfeb1b4f8aa

**Comment by gemarico** [comment]
> When press upload photo or video, url is modified to
> http://localhost:3000/?description=#/uploadRoute
> The same component is been used by NewRoute and that is not happening.

Since there is 2 buttons that perform an submit action you have to put them out of the form.

**Comment by uo246355** [comment]
Done and working
